export {
  AuthDrawer,
  DEFAULT_CONFIG,
  DEFAULT_COPY,
  OAUTH_PROVIDER_IDS,
  createAuthTriggerStore,
  defaultLabelForOAuthProvider,
  resolveOAuthVisibleCount,
  useScrollOpenTrigger,
} from "@remcostoeten/auth-drawer";
export type {
  AuthBackdropConfig,
  AuthConfig,
  AuthConfigGroup,
  AuthOAuthOverflowConfig,
  AuthCopyConfig,
  AuthPresentationConfig,
  AuthTriggerConfig,
  AuthTriggerEvent,
  AuthTriggerStore,
  AuthUiConfig,
  AuthVisualConfig,
  DrawerMode,
  DrawerPosition,
  MotionSettings,
  OAuthProvider,
  ResolvedAuthCopyConfig,
} from "@remcostoeten/auth-drawer";
